before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ibV7W5noHfJ0rkeQx+GSYyplUP9c7rf2b/B9gipuTbk6BJxcGklYGyLwF3Mgq0wgYDBDgPv0zICZ+bvGJ9i7cErivR6g0HfxI5QUUGTqFfw2C40iP13wi8ADN9D33L1Q2jmApWIKM+eOIHxTGS14kvXk46kkqKESvqREosWNDlnZ1LCOspIwGBnp6dZjcVUDG09hWSDw/k0eqD98J22zhYOxbAhTZcrldQyL8yAzh4VDl41hMn+bxsmn6XE5xY8S/NRqDn9iPagl8Mp+fqiLdwcFL6sWt6mLfTXcOCqtQH34jCi7UWvwvKzH+tL/2tq9xd7364nDt3S+m0twHQtDhvO+DP5eR4vLUFkC6QS2kWVz6xwZKsLWn4rEjJLc/BuwruCMOVReDaPJgJ413bA13Qt+3eQYu7HyZgGjvNkyPuKvgSknyya2kmYhXerSsx32D+07Ykww8tetXOmJCI2MfTzwoQqSMW+VR/qyGT+EmU49DmW2CwasRnv13GCsCSFngO/fAYYtEygW+BbjvM25FCJQa0adE98Cc6hJp9osm/gzHHJB+mZvsBWIVeCk6NWvMPty8VCp4WhsSE3s6S+5zScptlZDiI+7pflGpJXHCij90t9YKER3Es2RqFrVfSEiw6eseWm3tRO4dl5xUfiFJugu5jwYWKWtNcNZJt5swH4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
